### ISSUE TITLE
About video frames and labels correspondence

### ISSUE THREAD

**Issue by SJTUwxz** [zcxu-eric/Ego4d_TalkNet_ASD#1]
Thanks for the detailed code!
I have a question regarding how you process the video frames and labels of a given trackid. For example, given trackid: **a1055434-9e9b-4d69-bac3-374a39f801da:track_85:0**. Its entry in active_speaker_train.csv is

> a1055434-9e9b-4d69-bac3-374a39f801da:track_85:0 77  30.0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 1619

But the timestamps of the video frames are not continuous in the json file. The 77 frames correspond to timestamps: _1619-1677_ & _1694-1711_. So I assume the labels also correspond to these timestamps. However, in the dataloader, 

> track = [bbox[i] for i in range(int(data[-1]), int(data[-1])+int(data[1])) if i in bbox]

 first retrieves _1619-1677_ and _1694, 1695_. Then interpolation is used to add the missing bboxes. So timestamps of these 77 frames are 1619-1694. But the labels don't match these timestamps. So I'd like to know if this might be an issue or not. 
Thanks!

**Comment by zcxu-eric** [comment]
Hello, 

Ego4D does not provide the same labels as AVA Active Speaker Detection dataset. Active speaker labels used here are generated from the VAD labels. The speaker who is speaking and has a visible face will be labeled as active speaker. But this may differ from AVA's annotation guideline. VAD results do not always align with the faces in the field of view. That's why we interpolate the faces. 

These labels are also not strictly correct because we cannot verify each frame manually. Our motivation is to validate whether training on Ego4D dataset can improve the final diarization results for Ego4D AVD becnhmark.

**Comment by SJTUwxz** [comment]
Sorry for late reply! And thank you for the quick response! Sorry I might cause some confusions in the question. After reading your code, I found that in some cases, your dataloader will load the videos of one clip but use annotations of another clip.

For this video clip with trackid : a1055434-9e9b-4d69-bac3-374a39f801da:track_85:0, the video clip that your dataloader loads (including interpolation) is of frame 1619-1694. And the labels of this clip that the dataloader uses belong to frame 1619-1677 and frame 1694-1711. There is a difference between video frames and labels.

**Comment by zcxu-eric** [comment]
Hello, I'm not sure what is the reason for this inconsistency. Is this the error from code or the preprocessed labels?

**Comment by SJTUwxz** [comment]
Hey! The preprocessed labels in the annotated bbox json file have inconsistent timestamps for some video clips. I don't think it's an error. But in the dataloader code it seems to assume that the timestamps are consistent. Thanks!

**Comment by zcxu-eric** [comment]
> Hey! The preprocessed labels in the annotated bbox json file have inconsistent timestamps for some video clips. I don't think it's an error. But in the dataloader code it seems to assume that the timestamps are consistent. Thanks!

There are errors in the preprocessed labels. These are actually generated by ourselves cuz ego4d doesn't provide labels for active speaker detection. If this issue has side effect on your research, my suggestion is to regenerate these labels for ASD.

**Comment by SJTUwxz** [comment]
Hi! Thanks for your quick response and suggestion! I will check their paper and try to regenerate the labels.
