### ISSUE TITLE
Face crop augmentation

### ISSUE THREAD

**Issue by SAGNIKMJR** [zcxu-eric/Ego4d_TalkNet_ASD#4]
Hi @zcxu-eric ,

Could you provide some intuition behind the following code (see screenshot) for face crop augmentation in `dataLoader.py`. Specifically, I don't understand what you achieve through lines 111 and 114. I couldn't find any such step in the original TalkNet repo (https://github.com/TaoRuijie/TalkNet-ASD) or any mention of it in the TalkNet/Ego4D paper. 

<img width="773" alt="Screenshot 2023-02-24 at 9 47 24 PM" src="https://user-images.githubusercontent.com/19723914/221334761-1b6f239b-bedd-4015-9c65-ac899e59ddff.png">

**Comment by zcxu-eric** [comment]
Hi, the motivation is to crop a sqaure region with the face located in the center of the image. You may find the source [here](https://github.com/TaoRuijie/TalkNet-ASD/blob/85b37afc32bedcadd8b5dfbc7f69298a76de279b/demoTalkNet.py#L177) from TalkNet.
