### ISSUE TITLE
Experiment environment setup

### ISSUE THREAD

**Issue by zhuxj821** [zcxu-eric/Ego4d_TalkNet_ASD#7]
I would like to ask about your experiment environment setup. How many and what type of GPU cards are being used, and approximately how long does it take to train one epoch?

**Comment by zcxu-eric** [comment]
Hi, it has been a long time since the development of this repo. I can only remember that I used 2 RTX4090 GPUs.

**Comment by zhuxj821** [comment]
> Hi, it has been a long time since the development of this repo. I can only remember that I used 2 RTX4090 GPUs.

OK,thank you.
